### ISSUE TITLE
FDR collection tool retrieving documents as `txt` format

### ISSUE THREAD

**Issue by keighrim** [lappsgrid-incubator/GalaxyMods#10]
Files retrieved by FDR  "create collection" tool are marked as `txt`, although the tool config is [explicitly specifying](https://github.com/lappsgrid-incubator/GalaxyMods/blob/develop/tools/fdr/create_collection.xml#L13) the format to be `lif` . 
Maybe the tool is [creating files with `.txt` extension](https://github.com/lappsgrid-incubator/GalaxyMods/blob/develop/tools/fdr/create_collection.lsd#L21) and then galaxy is trying to find files and [dynamically mark](https://github.com/lappsgrid-incubator/GalaxyMods/blob/develop/tools/fdr/create_collection.xml#L14) them using their extension?

**Comment by ksuderman** [comment]
it turns out it is the LSD wrapper that is using a .txt extension.  Interesting the file extension supersedes the *format* specified in the XML config.

**Comment by keighrim** [comment]
closed via #13
